services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: logs
    ports:
      - '5432:5432'

  producer:
    build: ./producer-service
    ports:
      - '8001:8000'

  processor:
    build: ./processor-service
    depends_on:
      - redis
      - postgres

  api:
    build: ./api-service
    ports:
      - '8002:8000'
